// MNetworkVarNames = "bool m_bIsPlayingBack"
// MNetworkVarNames = "bool m_bPaused"
// MNetworkVarNames = "bool m_bMultiplayer"
// MNetworkVarNames = "bool m_bAutogenerated"
// MNetworkVarNames = "float32 m_flForceClientTime"
// MNetworkVarNames = "uint16 m_nSceneStringIndex"
// MNetworkVarNames = "CHandle< C_BaseFlex > m_hActorList"
class C_SceneEntity : public C_PointEntity
{
	// MNetworkEnable
	bool m_bIsPlayingBack;
	// MNetworkEnable
	bool m_bPaused;
	// MNetworkEnable
	bool m_bMultiplayer;
	// MNetworkEnable
	bool m_bAutogenerated;
	// MNetworkEnable
	// MNetworkChangeCallback = "OnResetClientTime"
	float32 m_flForceClientTime;
	// MNetworkEnable
	// MNetworkPriority = 32
	uint16 m_nSceneStringIndex;
	bool m_bClientOnly;
	CHandle< C_BaseFlex > m_hOwner;
	// MNetworkEnable
	// MNetworkPriority = 32
	C_NetworkUtlVectorBase< CHandle< C_BaseFlex > > m_hActorList;
	bool m_bWasPlaying;
	CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents;
	float32 m_flCurrentTime;
};
