class C_SceneEntity
{
	bool m_bIsPlayingBack;
	bool m_bPaused;
	bool m_bMultiplayer;
	bool m_bAutogenerated;
	float32 m_flForceClientTime;
	uint16 m_nSceneStringIndex;
	bool m_bClientOnly;
	CHandle< C_BaseFlex > m_hOwner;
	C_NetworkUtlVectorBase< CHandle< C_BaseFlex > > m_hActorList;
	bool m_bWasPlaying;
	CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents;
	float32 m_flCurrentTime;
};
