----============ Copyright (c) Valve Corporation, All rights reserved. ==========
--require "animationsystem.sequences"
--DoIncludeScript( "animation/sequence_functions/sequence_functions", getfenv(1) )
--DoIncludeScript( "animation/items/legion_commander/lotfl_subsequences.lua", getfenv(1) )
--
----
---- define final sequences
----
--
---- (standalone cloth ripple gesture)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_cloth_gesture",
--        looping = true,
--        sequences = {
--            { "@lotfl_pta_overlay" }
--        },
--        --weightlist = "cape",
--        activities = {
--            { name = "ACT_SCRIPT_CUSTOM_0", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--
--    }
--)
--
---- (idle) 
--model:CreateSequence(
--    {
--        name = "lotfl_pta_idle",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_idle" }
--        }, 
--        addlayer = { "@lotfl_pta_idle_layer" },
--        activities = {
--            { name = "ACT_DOTA_IDLE", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_idle",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_idle" }
--        }, 
--        addlayer = { "@lotfl_normal_idle_layer" },
--        activities = {
--            { name = "ACT_DOTA_IDLE", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (press the attack) 
--model:CreateSequence(
--	{
--		name = "lotfl_pta_press_anim_self",
--		sequences = {
--			{ "@legion_commander_press_anim" }
--		},
--        addlayer = { "@lotfl_pta_press_layer" },
--		activities = {
--			{ name = "ACT_DOTA_CAST_ABILITY_2", weight = 1 },
--			{ name = "self", weight = 1 },
--			{ name = "press_the_attack", weight = 1 },
--			{ name = "fallen_legion", weight = 1 }
--		}
--	}
--)
--model:CreateSequence(
--	{
--		name = "lotfl_normal_press_anim_self",
--		sequences = {
--			{ "@legion_commander_press_anim" }
--		},
--        --addlayer = { "@lotfl_normal_press_layer" },
--        addlayer = { "@lotfl_pta_press_layer" },
--		activities = {
--			{ name = "ACT_DOTA_CAST_ABILITY_2", weight = 1 },
--			{ name = "self", weight = 1 },
--			{ name = "fallen_legion", weight = 1 }
--		}
--	}
--)
--model:CreateSequence(
--	{
--		name = "lotfl_pta_press_anim",
--		sequences = {
--			{ "@legion_commander_press_anim" }
--		},
--        addlayer = { "@lotfl_normal_press_layer" }, 
--		activities = {
--			{ name = "ACT_DOTA_CAST_ABILITY_2", weight = 1 },
--			{ name = "press_the_attack", weight = 1 },
--			{ name = "fallen_legion", weight = 1 }
--		}
--	}
--)
--model:CreateSequence(
--	{
--		name = "lotfl_normal_press_anim",
--		sequences = {
--			{ "@legion_commander_press_anim" }
--		},
--        addlayer = { "@lotfl_normal_press_layer" },
--		activities = {
--			{ name = "ACT_DOTA_CAST_ABILITY_2", weight = 1 },
--			{ name = "fallen_legion", weight = 1 }
--		}
--	}
--)
--
---- (attack)
---- and attack1, since they use the same start-/end- frame range
--model:CreateSequence(
--    {
--        name = "lotfl_pta_attack0",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_attack_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_attack_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_attack0",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_attack_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_attack_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_attack1",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_attack1_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_attack_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_attack1",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_attack1_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_attack_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (attack2)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_attack2",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_attack2_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_attack2_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_attack2",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_attack2_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_attack2_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (moment of courage)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_moment_of_courage",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_momentofcourage_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_moc_layer" },
--        activities = {
--            { name = "ACT_DOTA_MOMENT_OF_COURAGE", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_moment_of_courage",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_momentofcourage_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_moc_layer" },
--        activities = {
--            { name = "ACT_DOTA_MOMENT_OF_COURAGE", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (overwhelming odds)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_overodds",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_overodds_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_overodds_layer" },
--        activities = {
--            { name = "ACT_DOTA_MOMENT_OF_COURAGE", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_overodds",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_overodds_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_overodds_layer" },
--        activities = {
--            { name = "ACT_DOTA_MOMENT_OF_COURAGE", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (duel)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_duel",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_duel_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_duel_layer" },
--        activities = {
--            { name = "ACT_DOTA_CAST_ABILITY_4", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_duel",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_duel_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_duel_layer" },
--        activities = {
--            { name = "ACT_DOTA_CAST_ABILITY_4", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (duel kill)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_duel_kill",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_duel_kill_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_duel_kill_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "duel_kill", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_duel_kill",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_duel_kill_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_duel_kill_layer" },
--        activities = {
--            { name = "ACT_DOTA_ATTACK", weight = 1 },
--            { name = "duel_kill", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (flail)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_flail",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_flail_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_flail_layer" },
--        activities = {
--            { name = "ACT_DOTA_FLAIL", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_flail",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_flail_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_flail_layer" },
--        activities = {
--            { name = "ACT_DOTA_FLAIL", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (forcestaff friendly)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_forcestaff_friendly",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_forcestaff_friendly_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_forcestaff_layer" },
--        activities = {
--            { name = "ACT_DOTA_FLAIL", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_forcestaff_friendly",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_forcestaff_friendly_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_forcestaff_layer" },
--        activities = {
--            { name = "ACT_DOTA_FLAIL", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (stun)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_stun",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_stun_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_stun_layer" },
--        activities = {
--            { name = "ACT_DOTA_DISABLED", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_stun",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_stun_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_stun_layer" },
--        activities = {
--            { name = "ACT_DOTA_DISABLED", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (death)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_death",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_die" }
--        }, 
--        addlayer = { "@lotfl_pta_death_layer" },
--        activities = {
--            { name = "ACT_DOTA_DIE", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_death",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_die" }
--        }, 
--        addlayer = { "@lotfl_normal_death_layer" },
--        activities = {
--            { name = "ACT_DOTA_DIE", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (forcestaff_enemy)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_forcestaff_enemy",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_forcestaff_enemy" }
--        }, 
--        addlayer = { "@lotfl_pta_forcestaff_enemy_layer" },
--        activities = {
--            { name = "ACT_DOTA_FLAIL", weight = 1 },
--            { name = "forcestaff_enemy", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_forcestaff_enemy",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_forcestaff_enemy" }
--        }, 
--        addlayer = { "@lotfl_normal_forcestaff_enemy_layer" },
--        activities = {
--            { name = "ACT_DOTA_FLAIL", weight = 1 },
--            { name = "forcestaff_enemy", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (forcestaff_end)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_forcestaff_end",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_forcestaff_end" }
--        }, 
--        addlayer = { "@lotfl_pta_forcestaff_end_layer" },
--        activities = {
--            { name = "ACT_DOTA_FORCESTAFF_END", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_forcestaff_end",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_forcestaff_end" }
--        }, 
--        addlayer = { "@lotfl_normal_forcestaff_end_layer" },
--        activities = {
--            { name = "ACT_DOTA_FORCESTAFF_END", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
---- (spawn)
--model:CreateSequence(
--    {
--        name = "lotfl_pta_spawn",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_spawn_anim" }
--        }, 
--        addlayer = { "@lotfl_pta_spawn_layer" },
--        activities = {
--            { name = "ACT_DOTA_SPAWN", weight = 1 },
--            { name = "press_the_attack", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--model:CreateSequence(
--    {
--        name = "lotfl_normal_spawn",
--        looping = true, 
--        sequences = {
--            { "@legion_commander_spawn_anim" }
--        }, 
--        addlayer = { "@lotfl_normal_spawn_layer" },
--        activities = {
--            { name = "ACT_DOTA_SPAWN", weight = 1 },
--            { name = "fallen_legion", weight = 1 }
--        }
--    }
--)
--
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
----------------------------------------------------------------------------EOF---
