--[[ constants.lua ]]

--------------------------------------------------------------------------------
-- Integer constants
--------------------------------------------------------------------------------
-- General
_G.nHERO_MAX_LEVEL = 25

_G.nBASE_GOLD_BAG_DROP_RATE = 30
_G.nMAX_RESPAWNS = 5
_G.nSTARTING_RESPAWNS = 1
_G.nCHECKPOINT_REVIVES = 1
_G.nREVIVE_COST = 1
_G.nBUYBACK_COST = 1
_G.nREVIVE_HP_PCT = 25

-- Creature
_G.nROAMER_MAX_DIST_FROM_SPAWN = 2048
_G.nBOSS_MAX_DIST_FROM_SPAWN = 0

_G.nSQUADMEMBER_MAX_SPAWN_DIST = 250
_G.nSQUADMEMBER_MAX_WANDER_DIST = 300

_G.nCREATURE_RESPAWN_TIME = 60

_G.ZONE_TYPE_EXPLORE = 	0
_G.ZONE_TYPE_SURVIVAL = 1
_G.ZONE_TYPE_HOLDOUT = 	2
_G.ZONE_TYPE_ASSAULT = 	3

_G.QUEST_EVENT_ON_ZONE_ACTIVATE 			= 0
_G.QUEST_EVENT_ON_DIALOG 					= 1
_G.QUEST_EVENT_ON_ZONE_EVENT_FINISHED 		= 2
_G.QUEST_EVENT_ON_QUEST_ACTIVATE 			= 3
_G.QUEST_EVENT_ON_QUEST_COMPLETE 			= 4
_G.QUEST_EVENT_ON_ENEMY_KILLED 				= 5
_G.QUEST_EVENT_ON_KEY_ITEM_RECEIVED			= 6
_G.QUEST_EVENT_ON_DIALOG_ALL_CONFIRMED   	= 7
_G.QUEST_EVENT_ON_TREASURE_OPENED			= 8

_G.ZONE_STAT_KILLS 			= 0
_G.ZONE_STAT_DEATHS			= 1
_G.ZONE_STAT_ITEMS			= 2
_G.ZONE_STAT_GOLD_BAGS		= 3
_G.ZONE_STAT_POTIONS		= 4
_G.ZONE_STAT_REVIVE_TIME	= 5
_G.ZONE_STAT_DAMAGE 		= 6
_G.ZONE_STAT_HEALING		= 7

_G.ZONE_STAR_CRITERIA_TIME 				= 0
_G.ZONE_STAR_CRITERIA_DEATHS 			= 1
_G.ZONE_STAR_CRITERIA_KILLS				= 2
_G.ZONE_STAR_CRITERIA_QUEST_COMPLETE	= 3